export enum AppStatus {
  OK = "OK",
  SUCCESS = "SUCCESS",
  CONFLICT = "CONFLICT",
  ERROR = "ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
